[appearance]
prefer_no_csd = true
corner_radius = 20
outer_border_width = 1
border_width = 1
drag_opacity = 1.0

[appearance.blur]
enabled = true
optimized = true
radius = 2        # 0-100
noise = 0.02      # 0.0-1.0
brightness = 1.05 # 0.0-2.0
contrast = 0.9    # 0.0-2.0
saturation = 1.5

[appearance.shadow]
softness = 80
offset_x = 0
offset_y = 25


[input.cursor]
theme = "Bibata-Modern-Classic" # empty = environment/default Xcursor theme
size = 24                       # 1-512
hardware_cursor = true
hide_when_typing = true
hide_timeout_ms = 0             # 0-3600000, 0 disables hiding
